# Generated by Django 4.0 on 2022-02-11 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_alter_emailuser_id'),
        ('tasks', '0003_alter_task_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='EffortSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('R', 'Running'), ('P', 'Paused')], max_length=1)),
                ('last_active', models.DateTimeField()),
                ('duration', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.emailuser')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tasks.task')),
            ],
        ),
        migrations.CreateModel(
            name='Effort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts', models.DateTimeField()),
                ('duration', models.IntegerField()),
                ('description', models.CharField(blank=True, default='', max_length=512)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='effort_set', to='core.emailuser')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='effort_set', to='tasks.task')),
            ],
        ),
        migrations.AddIndex(
            model_name='effort',
            index=models.Index(fields=['-starts'], name='effort_effo_starts_9ac05a_idx'),
        ),
    ]
