# Generated by Django 4.0 on 2022-02-15 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('effort', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='effortsession',
            name='description',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
