# Generated by Django 3.2.3 on 2021-05-22 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('effort', '0003_auto_20210406_1804'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='effort',
            name='effort_effo_ended_2d810a_idx',
        ),
        migrations.RenameField(
            model_name='effort',
            old_name='started',
            new_name='starts',
        ),
        migrations.RemoveField(
            model_name='effort',
            name='ended',
        ),
        migrations.AddField(
            model_name='effort',
            name='duration',
            field=models.IntegerField(default=30),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='effort',
            index=models.Index(fields=['-starts'], name='effort_effo_starts_9ac05a_idx'),
        ),
    ]
