# Generated by Django 3.2.3 on 2021-08-09 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('effort', '0004_auto_20210522_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='effort',
            name='description',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
