# Generated by Django 3.1.7 on 2021-04-04 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0002_auto_20210330_1449'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewPeriodConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('base_duration', models.CharField(choices=[('D', 'Day'), ('W', 'Week'), ('M', 'Month'), ('Y', 'Year')], max_length=1)),
                ('multiplier', models.IntegerField()),
                ('starts', models.DateTimeField()),
                ('index_type', models.CharField(choices=[('WN', 'Week Number'), ('MN', 'Month Name'), ('IN', 'Integer Index')], max_length=2)),
                ('index_reset_duration', models.CharField(choices=[('D', 'Day'), ('W', 'Week'), ('M', 'Month'), ('Y', 'Year')], max_length=1)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_period_configurations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts', models.DateTimeField()),
                ('ends', models.DateTimeField()),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reviews.reviewperiodconfiguration')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_periods', to=settings.AUTH_USER_MODEL)),
                ('planned_tasks', models.ManyToManyField(related_name='review_periods', to='tasks.Task')),
            ],
        ),
    ]
