# Generated by Django 3.2 on 2021-05-04 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20210406_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewperiod',
            name='ends',
        ),
        migrations.RemoveField(
            model_name='reviewperiod',
            name='starts',
        ),
        migrations.AddField(
            model_name='reviewperiod',
            name='index',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviewperiod',
            name='review_period_index',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reviewperiod',
            name='configuration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.reviewperiodconfiguration'),
        ),
        migrations.AlterField(
            model_name='reviewperiodconfiguration',
            name='index_type',
            field=models.CharField(choices=[('WN', 'Week Number'), ('FN', 'Fortnight Number'), ('MN', 'Month Name'), ('QN', 'Quarter Number'), ('IN', 'Integer Index')], max_length=2),
        ),
    ]
