# Generated by Django 3.2 on 2021-05-12 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20210504_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewperiodconfiguration',
            name='index_reset_duration',
            field=models.CharField(choices=[('Y', 'End of Year'), ('N', 'Never')], max_length=1),
        ),
    ]
