# Generated by Django 3.2.3 on 2021-05-19 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_alter_reviewperiodconfiguration_index_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewperiodconfiguration',
            name='active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
