version: "3.9"

services:
  db:
    env_file:
      - ./.env.prod

  web:
    build:
      dockerfile: Dockerfile.prod
    command: gunicorn threes.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - ./.env.prod
    volumes:
      - static_files:/static

  web_app:
    command: npm run productionBuild
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    volumes:
      - static_files:/output

  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web
      - web_app
    volumes:
      - static_files:/static

volumes:
  static_files:
