version: "3.8"

services:
  db:
    env_file:
      - ./.env.prod

  web_app:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    image: threes-frontend:latest

  web:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    image: threes-backend:latest
    command: gunicorn threes.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - ./.env.prod

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    ports:
      - 1337:80
    depends_on:
      - web
    container_name: threes-nginx
    depends_on:
      - web_app
