version: "3.9"

services:
  db:
    env_file:
      - ./.env.prod
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn threes.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - ./.env.prod
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web
      # TODO: - web_app
