apiVersion: v1
kind: PersistentVolume
metadata:
  name: threes-db-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/radek/projects/threes/.data"
