apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -f docker-compose.prod.yml
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: web-app
  name: web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: web-app
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -f docker-compose.prod.yml
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: web-app
    spec:
      containers:
        - args:
            - npm
            - run
            - productionBuild
          image: web-app
          name: web_app
          resources: {}
          volumeMounts:
            - mountPath: /output
              name: static-files
      restartPolicy: Always
      volumes:
        - name: static-files
          persistentVolumeClaim:
            claimName: static-files
status: {}
