apiVersion: v1
kind: ConfigMap
metadata:
  name: threes-configmap
data:
  django-debug: {{ .Values.djangoDebug | quote }}
  django-allowed-hosts: {{ .Values.hostIp | cat "127.0.0.1 [::1]" | quote }}
