# syntax=docker/dockerfile:1
FROM python:3.10

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

RUN apt-get update
RUN apt install -y netcat

RUN pip install pipenv

WORKDIR /setup
COPY ./Pipfile.lock .
COPY ./Pipfile .
RUN pipenv install --system --deploy --ignore-pipfile --dev

RUN mkdir -p /var/log/threes
RUN chmod 700 /var/log/threes

WORKDIR /code/backend/
