# Generated by Django 3.1.7 on 2021-03-30 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='emailuser',
            managers=[
            ],
        ),
    ]
