apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: threes-db-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: {{ eq .Values.environment "digitalocean" | ternary "do-block-storage" "" }}
