{{ if eq .Values.environment "desktop" }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: threes-db-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/radek/projects/threes/.data"
{{ end }}
