apiVersion: apps/v1
kind: Deployment
metadata:
  name: threes-db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: threes-db
  template:
    metadata:
      labels:
        app: threes-db
    spec:
      volumes:
        - name: postgres-db-data
          persistentVolumeClaim:
            claimName: threes-db-pv-claim
      imagePullSecrets:
        - name: private-dockerhub
      containers:
        - name: threes-db
          image: rstibora/threes-db:{{ .Chart.Version }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: threes-db-secret
                  key: db-postgres-password
            - name: THREES_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: threes-db-secret
                  key: db-threes-password
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              subPath: postgres
              name: postgres-db-data
