apiVersion: v1
kind: Secret
metadata:
  name: threes-db-secret
type: Opaque
data:
  db-postgres-password: {{ .Values.secrets.dbPostgresPassword | required "Non-empty password is required for the DB account 'Postgres'." | b64enc | quote }}
  db-threes-password: {{ .Values.secrets.dbThreesPassword | required "Non-empty password is required for the DB account 'threes'." | b64enc | quote }}
