apiVersion: v1
kind: Secret
metadata:
  name: threes-db-secret
type: Opaque
data:
  db-postgres-password: cG9zdGdyZXMK # Password for 'postgres' db user account.
  db-threes-password: dGhyZWVzCg== # Password for 'threes' db user account.
