export enum Mutations {
    UPDATE_EFFORTS = "UPDATE_EFFORTS",
    UPDATE_REVIEWS = "UPDATE_REVIEWS",
    UPDATE_REVIEW_CONFIGURATIONS = "UPDATE_REVIEW_CONFIGURATIONS",
    UPDATE_USER_REVIEW_CONFIGURATIONS = "UPDATE_USER_REVIEW_CONFIGURATIONS",
    UPDATE_SESSION = "UPDATE_SESSION",
    UPDATE_TASKS = "UPDATE_TASKS",
}

export enum Actions {
    CREATE_EFFORT = "CREATE_EFFORT",
    CREATE_TASK = "CREATE_TASK",

    DESTROY_EFFORT = "DESTROY_EFFORT",

    FETCH_EFFORTS = "FETCH_EFFORTS",
    FETCH_RESOURCE = "FETCH_RESOURCE",
    FETCH_REVIEWS = "FETCH_REVIEWS",
    FETCH_REVIEW_CONFIGURATIONS = "FETCH_REVIEW_CONFIGURATIONS",
    FETCH_TASKS = "FETCH_TASKS",
    FETCH_USER_REVIEW_CONFIGURATIONS = "FETCH_USER_REVIEW_CONFIGURATIONS",

    REFRESH_TOKEN = "REFRESH_TOKEN",

    UPDATE_EFFORT = "UPDATE_EFFORT",
    UPDATE_TASKS = "UPDATE_TASKS",
}
