apiVersion: apps/v1
kind: Deployment
metadata:
  name: threes-static-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: threes-static
  template:
    metadata:
      labels:
        app: threes-static
    spec:
      imagePullSecrets:
        - name: private-dockerhub
      containers:
        - name: threes-static
          image: rstibora/threes-static:{{ .Chart.Version }}
          imagePullPolicy: {{ .Values.imagePullPolicy | quote }}
          ports:
            - containerPort: 80
